### PR TITLE
New Website

### PR DESCRIPTION
**Pull request by meyerzinn**
A preview can be found at [https://aniskywalker.com](https://aniskywalker.com).

I built a new website for the Climate Mirror project. It's a bit slow (~1-2 seconds) on first download, but from there it should be lightning fast. Please note: wherever this is hosted, use VERY GOOD caching. Cache basically everything. It's a big initial download.

Some screenshots (on different browsers):

Chrome 55.0.2883.75 / Debian Testing (Lenny)

Chrome 10.0.612.1 / Windows 2008 R2 (Server)

Firefox 22.0 / Windows 7

Midori 0.4 / Ubuntu 9.10 (Karmic Koala)

Epiphany 3.14.1 / Debian Testing (Lenny)

Opera 12.02 / Debian 6.0 (squeeze)

Rekonq 2.4.2 / Ubuntu 12.04 LTS (Precise Pangolin)

You get the idea :) On mobile:
According to Google :)

### CODE REVIEW

**Comment by meyerzinn** [comment]
New preview with pagespeed active. https://aniskywalker.com, should drastically reduce page load time.

**Comment by meyerzinn** [comment]
Some weird issue where FontAwesome is required to maintain header spacing. No clue why but it's ~20kb and 100% cacheable so I'm not dealing with it.

**Comment by meyerzinn** [comment]
@nickrsan when can this be merged?

**Comment by meyerzinn** [comment]
Taking down the aniskywalker.com mirror soon.

**Comment by nickrsan** [comment]
Merging - I'll make a few edits before it's live.

**Comment by nickrsan** [comment]
Hey Meyer,

Quick question - do you have information on the licensing for these images? I've used the one with the US at night before, so I'm not concerned about that one. It looks like the Earth image came from here: https://commons.wikimedia.org/wiki/File:NASA_Earth_America_2010.jpg

The two I'm wondering about are the header image and the favicon. Could you note sources for those? Thanks for the new design!

**Comment by meyerzinn** [comment]
All images except from the favicon (same as the logo) came from unsplash.com, licensed under Creative Commons Zero.

[Header Background](https://unsplash.com/photos/aZ4OSja8LD0): by Kamal J, licensed under Creative Commons Zero
[US at Night From Space](http://earthobservatory.nasa.gov/IOTD/view.php?id=79800): by NASA, is public domain.
[Earth from Space](https://commons.wikimedia.org/wiki/File:NASA_Earth_America_2010.jpg): by NASA, is public domain.
[Gee, Thanks](http://chrispiascik.com/daily-drawings/gee-thanks/): Copyright Chris Piascik, used under fair use laws (non-profit use), can be swapped out easily if needed.
[Heart](https://unsplash.com/photos/cAtzHUz7Z8g): by Tim Marshall, licensed under Creative Commons Zero
[Logo/Icon](http://www.iconarchive.com/show/small-n-flat-icons-by-paomedia/globe-icon.html): by Paomedia Sarl, dedicated to the public domain.

**Pull request merged**
